config/routes.rb
RxchecklistApp::Application.routes.draw do
  

  

  devise_for :users 
  resources :users 

  get "page/index"

 
  resources :tasks 
  resources :about, :only => [:index]

  resources :explore 
  resources :checklists do 
    resources :checklist_runs
  end 

  

  root :to => 'page#index'

end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
  attr_accessible :title, :description, :user_id, :tasks_attributes 
  validates_presence_of :title
  validates_presence_of :user_id
  belongs_to :user
  has_many :tasks, :dependent => :destroy
  has_many :checklist_runs, :dependent => :destroy
  accepts_nested_attributes_for :tasks 
  
end

app/models/checklist_run.rb
class ChecklistRun < ActiveRecord::Base
  attr_accessible :checklist, :user, :task_completions_attributes
  belongs_to :checklist 
  belongs_to :user

  has_many :task_completions, :dependent => :destroy
  accepts_nested_attributes_for :task_completions
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :checklist_id, :name, :position
    validates_presence_of :name
    belongs_to :checklist

end

app/models/task_completion.rb
class TaskCompletion < ActiveRecord::Base
  attr_accessible :completed, :task, :checklist_run,
    :checked_off_at, :checklist_run_id, :state, :task_id,
    :task_completions_attributes

  belongs_to :checklist_run
  belongs_to :task

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :checklists, :dependent => :destroy
  has_many :checklist_runs, :dependent => :destroy
  has_many :completed_checklists, 
    through: :checklist_runs,
    readonly: true, 
    source: :checklist 


end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

def after_sign_in_path_for(resource)
  explore_index_path 
end

end

app/controllers/checklist_runs_controller.rb
class ChecklistRunsController < ApplicationController

  def new
    @checklist = Checklist.find(params[:checklist_id])
    @checklist_run = @checklist.checklist_runs.create(user: current_user)
    build_task_completions
  end 
  
  def update
    @checklist_run = ChecklistRun.find(params[:id])
    if @checklist_run.update_attributes(params[:checklist_run])
      redirect_to user_path(current_user)
    else
      # do something else
    end
  end

  def show
    @checklist_run = ChecklistRun.find(params[:id])
  end 

  protected
  def build_task_completions
    @checklist.tasks.each do |t|
    @checklist_run.task_completions.create(task: t)
    end
  end



end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController

  def index
  end 

  def new
    if !current_user
      redirect_to new_user_registration_path
    else
    @checklist = current_user.checklists.build 
    end
  end 

  def create

    @checklist = current_user.checklists.new(params[:checklist])

    if @checklist.save!
      redirect_to @checklist, notice: 'checklist successfully created'
    else
      render action: 'new'
    end 
  end 

  def show
    @checklist = Checklist.find(params[:id])
  end 

  def destroy 
    
    @checklist = Checklist.find(params[:id])
  if @checklist.user == current_user
    @checklist.destroy
    redirect_to user_path(current_user)
  else
    redirect_to @checklist
    end 
  end 

end

app/controllers/explore_controller.rb
class ExploreController < ApplicationController
  def index
    # @checklists = Checklist.all
    @q = Checklist.search(params[:q])
    @checklists = @q.result.page(params[:page]).per(5)

  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  helper_method :resource, :resource_name, :devise_mapping 

  def index
  end



protected 

 def resource
    @resource ||= User.new
  end

  def resource_name
    :user
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end




end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController 

  def index
  end 

  def new
    @task = Task.new
  end 

  def create
    @task = Task.new(params[:task])

    if @task.save!
      redirect_to new_task_path, notice: 'task successfully created'
    else
      render action: 'new'
    end 
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def new
    @user = User.new 
  end

  def create
    @user = User.new(params[:user])
  end

  def show
    @checklist = Checklist.where(:user_id => current_user)
  end 
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checklist_run_helper.rb
module ChecklistRunHelper
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/explore_helper.rb
module ExploreHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/about/index.html.erb
<div class="row">
      <div class="span12">
<h1>Inspiration for RxCheck</h1>

<p>The below excerpt is from <em>The Checklist Manifesto</em> - a book by Atul Gawande, general surgeon and assistant professor at Harvard Medical School.  Dr. Gawande dictates that checklist's for the medical profession were created out of necessity due to the ever increasing complexity of treating medical issues and the high specialization of todays medical professionals.</p> 


<div class="row">
  <div class="row-images" align="center">
   <%= image_tag("manifesto.jpg", :alt => "The Checklist Manifesto", :class => "img-about" ) %>
  </div>
</div>


<h5>In a complex high-pressure environment, experts awlays come up against two main difficulties:</h5>

1. It's easy to overlook routine matters under the strain of pressing immediate demands<br>

2. People can lull themselves into skipping steps even when they remember them<br>
<br>

<strong>Checklists</strong> provide a protection against these two difficulties. By making the minimum necessary steps explicit and verifiable, a discipline is instilled which can lead to higher levels of performance.<br> 
                <strong class="excerpt">- The Checklist Manifesto </strong>
<br>
<br>
<h4>The Current Issue</h4>
<h5>There are two main issues with the current use of checklists:</h5> 

1. Internalization - a checklist created and used within one hospital or medical practice<br> 

2. Analyitics - paper checklists cannot record and analyze how a checklist is used, why its being used, and how to further optimize it<br>
<br>
<h4>One Step Further</h4> 
<h5>RxCheck is taking the idea of medical checklists one step further to remedy these issues:</h5>

1. Collaboration - share a checklist among the global medical community for all to use - "Network Effect"<br> 
2. Analysis - recording the use of individual checklists in order to optimize their use with the ulimate goal of increasing the quality of best practices   



Whats better, a checklist made for 1 hospital or a checklist made for 1000's of hospitals?  
</div>
</div>

<div id='project-url' align="center">
  <a href="https://github.com/sreedich/rxchecklist">To View My Project on GitHub Click Here</a>
</div>

app/views/checklist_runs/new.html.erb
<h1 align="center"><%= @checklist.title %></h1><br>

<div class="span12">
  <div id="gauge" style="width:350px; height:350px">
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th class="description">Description:</th>
      <th><%= @checklist.description %></th>
    </tr>

   
    <tr>
      <th>
        <div class="check-stats">0/<%= @checklist_run.task_completions.count %></div>
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody>

    <%= simple_form_for [@checklist, @checklist_run] do |f| %>
    <%= f.simple_fields_for :task_completions do |form| %>
    <tr>
      <td id="check-here"> <%= form.input :completed, as: :boolean, label: false %></td>
      <td><%= form.label :completed, label: form.object.task.name %></td>
    </tr>

    <% end %>
    <tr>
       <td></td>
       <td><%= f.submit 'Complete', :class => 'btn btn-create submit-it' %></td>
    </tr>
<% end %>

  </tbody>
</table>

<%# link_to 'Complete', new_checklist_checklist_run_path(@checklist) %>
<!-- leaving off here - look at the nested resources for checklist run and controller  -->

app/views/checklist_runs/show.html.erb
<h1 align="center"><%= @checklist_run.checklist.title %></h1>
<%# @checklist_run.checklist.task_completion %>


<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>


    <% @checklist_run.task_completions.each do |completion| %>
    <tr class="<%= 'success' if completion.completed %>">

      <td> <%= check_box_tag '', 1, completion.completed, :disabled => true  %></td>
      <td><%= completion.task.name %></td>   
    </tr>
    <% end %>

  

  </tbody>
</table>

<div align="center">
<%= link_to "Back", user_path(current_user), :class => 'btn btn-success btn-explore'  %>
</div>

app/views/checklists/new.html.erb
<div id="checklist-top">
  <p>Create a Checklist</p>
</div>
<hr>


<div class="row">
  <div class="checklist-new">
    <div class="span6">
      <%= simple_nested_form_for @checklist do |f| %>

        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.fields_for :tasks do |task_form| %>
        <%= task_form.link_to_remove "Remove Task", :class =>'check-link' %>
          <%= task_form.input :name, input_html: {rows: 3} %>
          
        <% end %>

        <div>
         <%= f.link_to_add "Add Task", :tasks, :class =>'check-link' %>
          <%= f.submit 'Create Checklist', :class => 'btn btn-create' %>
        </div>
   
      <% end %>
    </div>
  </div> 
  <div class="steps">
    <div class="span6">
      <h3>Steps to Create a New Checklist:</h3>
      <div class="check-steps">
      <h4>1. Add a title</h4>
      <h4>2. Add a description (optional)</h4>
      <h4>3. Add a new task or two or three or...</h4>
      <h4>4. Click Create Checklist </h4>
    </div>
    </div>
  </div>
</div>

app/views/checklists/show.html.erb
<div id="show-header">
  <h1 id="title-show" align="center"><%= @checklist.title %></h1><br>
</div>




<table class="table table-hover">
  <thead>
    <tr>
      <th class="description">Description:</th>
      <th><%= @checklist.description %></th>
    </tr>
  </thead>
  <tbody>

      <% @checklist.tasks.each do |task| %>

    <tr>
      <td id="check-show"> <%= check_box :nil, :nil %></td>
      <td> <%= task.name %> </td>
    </tr>
    <% end %> 
  
  </tbody>
</table>

<div align="center">
    <%= link_to 'Use Checklist', new_checklist_checklist_run_path(@checklist),  :class => 'btn btn-create' %>
</div>

   <%= link_to 'Delete', checklist_path(@checklist), method: :delete %>

app/views/explore/index.html.erb
<div align="center" id="explore-title">
  Explore
</div>

<div class="row">
  <div class='searching'>
    <div align="center">
      <div class='form-inline'>
      <%= search_form_for @q, url: explore_index_path, :builder => SimpleForm::FormBuilder do |f| %>
          <% f.label :title_cont, "Name contains" %>
          <%= f.text_field :title_cont, :placeholder => 'Search', :class => 'explore-search' %>
          <%= f.submit "Search", :class => 'btn btn-search' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="featured-list">
  <div class="pagination">
    <%= paginate @checklists  %>
  </div>

  <div id='featured'>Featured</div>

<table class="table table-hover fixed">
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
 
      <% @checklists.each do |c| %>
       <tr>
        <td id="explore-titles"> <%= c.title %></td>
        <td> <%= c.description %></td>
        <td id="see-details"><%= link_to 'See Details', checklist_path(c) %></td>
        </tr>
      <% end %>
 
</div>
 </tbody>
</table>


<div align="center">
<%= link_to "Create a New Checklist", new_checklist_path, :class => 'btn btn-success btn-explore'  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RxchecklistApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="#">RxCheck</a>
      <ul class="nav">
        <li><a href="/explore">Explore</a></li>
        <li><a href="/checklists/new">New Checklist</a></li>
        <li><a href="/about">About</a></li>
        <li>
          <% if user_signed_in? %>
            <%= link_to "Profile", user_path(current_user) %>
          <% else %>
            <!-- nothing -->
          <% end %>
        </li>
        <li><%= render 'devise/menus/login' %></li>
        <li><%= render 'devise/menus/signup' %></li>
      </ul>
      <div id="user_nav">

      </div>
    </div>
  </div>



    <div id="flash">
     <% flash.each do |key, value| -%>
     <%- unless key == :action %>
     <div class="alert alert-<%= value %>"><%=h value %></div>
     <%- end-%>
     <% end -%>
   </div>

   <div class="container">

    <%= yield %>

  <div class="row foot">
  </div>

    <hr>

    <footer>
      <div class="row">
        <div class="navbar span4">
          <ul class="nav">
            <li><a href="/explore">Explore</a></li>
            <li><a href="/checklists/new">New Checklist</a></li>
            <li><a href="/about">About</a></li>
          </ul>
        </div>
      </div>
    </footer>
  </div>

</body>
</html>

app/views/page/index.html.erb
<div class="jumbo">
  <div class="jumbo-image">
    <div class="row">
      <div class="span9">
        <h1 class="heading-static">Build a Better Checklist, Get Things Right, Quick & Simple.</h1>
        <p class="subheading-static">RxCheck is an Open Source Platform to Build, Use, and Share Medical Checklists among a Global Community of Medical Professionals.</p>
      </div>

      <div class="span3">
        <div class="sign-up-static">
          <%= render 'devise/registrations/form' %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="row-images" align="center">
    <div class="span4">
      <%= image_tag("cog.png", :alt => "Use It", :class => "img-static" ) %>
      <h3>Build It</h3>
      <p>Create Your Checklist</p>
    </div>

    <div class="span4" align="center">
      <%= image_tag("checker.png", :alt => "Use It", :class => "img-static" ) %>
      <h3>Use It</h3>
      <p>Use It On The Job</p>
     
    </div>

    <div class="span4" align="center">
       <%= image_tag("shareit.png", :alt => "Use It", :class => "img-static" ) %>
      <h3>Share It</h3>
      <p>Share It With The Community</p>
    </div>
  </div>
</div>

app/views/tasks/_task.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/tasks/new.html.erb
<p>Task</p>

<%= render 'task' %>

app/views/users/show.html.erb
<div class="row">
  <div class="your-check span6">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Your Checklists </th>
          <th></th>
        </tr>
      </thead>
      <tbody>

        <% current_user.checklists.each do |checklist|%>

        <tr>
          <td><%= checklist.title %></td>
          <td> <%= link_to 'See Details', checklist_path(checklist) %></td>
        </tr>
        <% end %>

      </tbody>
    </table>
  </div>



  <div class="used-check span6">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Used Checklists </th>
          <th></th>
        </tr>
      </thead>
      <tbody>

        <% current_user.checklist_runs.each do |run| %> 
        <%= link_to checklist_checklist_run_path(run.checklist, run) do %>

        <tr>
          <td><%= run.checklist.title  %></td>
          <td><%= link_to 'See Details', checklist_checklist_run_path(run.checklist, run) %></td>
        </tr>
        <% end %>
        <% end %> 

      </tbody>
    </table>
  </div>





</div>